Assignment-2

1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
num =[1,2,3,4,5]
print(num)
num.append(6)
print(num)
num.extend([7,8,9])
print(num)
num.insert(0,0)
print(num)
num.remove(0)
print(num)
num.pop()
print(num)
num.clear()
print(num)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8]
[]


2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [2]:
student_names = ("Alice", "Bob", "Charlie")
print(f"Original tuple: {student_names}")

try:
    # Attempt to change the second name
    student_names[1] = "David"
except TypeError as e:
    print(f"\nAn error occurred: {e}")

Original tuple: ('Alice', 'Bob', 'Charlie')

An error occurred: 'tuple' object does not support item assignment


we can't change the names its immutable


3.Create a set of integers with some duplicate values. Print the set and explain the output

In [3]:
set ={1,1,3,6,6,9,5,8,9}
print(set)

{1, 3, 5, 6, 8, 9}


Duplicate values (1, 6, 9) are removed automatically.

4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [4]:
Student= {
    "Name":"RISHI",
    "Age":"21",
    "City":"Hyderbad"
}
Student["Age"]="22"
Student["email"]="rishi11@gmail.com"
print(Student)

{'Name': 'RISHI', 'Age': '22', 'City': 'Hyderbad', 'email': 'rishi11@gmail.com'}


5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [5]:
i =18
if i >=18:
  print("eligible to vote")
else:
  print("not eligible to vote")

eligible to vote


6.Given a 'marks' variable, print the grade:

90 and above: 'A'
75–89: 'B'
50–74: 'C'
Below 50: 'Fail'

In [6]:
marks = int(input("enter the marks:"))
if marks >=90:
  print("A")
elif marks >=75 and marks <=89:
  print("B")
elif marks >=50 and marks <=74:
  print("C")
else:
  print("Fail")

enter the marks:99
A


7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative

In [7]:
num = int(input("enter the number:"))
if num>=0:
  print("positive")
  if num %2==0:
    print("even")
  else:
    print("odd")
else:
  print("negative")

enter the number:4
positive
even


SECTION-B

8.Create:

A scalar using np.array(5)
A 1D array with values 1 to 5
A 2D array (2x3) with values from 10 to 60 in steps of 10

In [8]:
import numpy as np
a = np.array(5)
print(a)

5


In [9]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:

import numpy as np
a=np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().



In [11]:
import numpy as np

array = np.random.randint(0,100,(4,4))
print(array)

[[27 27 15 49]
 [24 38 25 72]
 [69 48 87 80]
 [56 36 67 50]]


10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.



In [12]:
import numpy as np
import pandas as pd
array = np.array([
    [1,2,3],
     [4,5,6],
      [7,8,9]])
print(array)
df = pd.DataFrame(array,columns=['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


SECTION-C

11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:

Use .info(), .describe()
Select 'Name' and 'City' columns
Drop 'City' column
Fill any missing values in 'Salary' column with the mean
Remove any duplicate rows

In [13]:
import pandas as pd
import numpy as np

rows = [
    ['Alice', 25, 'New York', 50000],
    ['Bob', 30, 'London', 60000],
    ['Charlie', 35, 'Paris', 70000],
    ['David', 28, 'Berlin', 55000],
    ['Eve', 22, 'Tokyo', 45000],
    ['Frank', 40, 'Sydney', 80000],
    ['Grace', 27, 'Toronto', 52000],
    ['Heidi', 32, 'Madrid', 62000],
    ['Ivan', 29, 'Rome', 58000],
    ['Jack', 31, 'Chicago', 63000]
]


df = pd.DataFrame(rows, columns=['Name', 'Age', 'City', 'Salary'])


print(df.info())


print(df.describe())


print(df[['Name', 'City']])


df_dropped = df.drop(columns=['City'])


df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

df = df.drop_duplicates()


print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes
None
             Age        Salary
count  10.000000     10.000000
mean   29.900000  59500.000000
std     5.087021  10157.099323
min    22.000000  45000.000000
25%    27.250000  52750.000000
50%    29.500000  59000.000000
75%    31.750000  62750.000000
max    40.000000  80000.000000
      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
3    David    Berlin
4      Eve     Tokyo
5    Frank    Sydney
6    Grace   Toronto
7    Heidi    Madrid
8     Ivan      Rome
9     Jack   Chicago
      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie 